### ISSUE TITLE
l4d2_fix_deathspit and l4d2_spit_spread_patch

### ISSUE THREAD

**Issue by nikita1824** [Target5150/MoYu_Server_Stupid_Plugins#15]
Hello, as I understand, we have to delete l4d2_fix_deathspit plugin if we use l4d2_spit_spread_patch. But same fix in your plugin doesn't work properly.

**Comment by jensewe** [comment]
`l4d2_fix_deathspit` functionality is included so yes.
I didn't dig into how proper disabling puddle should be, and just copy-pasted codes from `l4d2_fix_deathspit`. So is it still doing damage?

**Comment by jensewe** [comment]
I think i got it, and seems it's solved with some changes. Will push an update soon.

**Comment by nikita1824** [comment]
Hello, thank you for your attention to this problem but invisible deathspit still occurs even after your recent updates.

**Comment by jensewe** [comment]
Which version are you using?
It will be appreciated if you can be more specific on how to reproduce it.

**Comment by nikita1824** [comment]
I'm sorry for not providing this information.
Plugin version 1.8
Sourcemod version 1.10.0.6495
ConVar settings:
-  l4d2_spit_spread_saferoom 0
-  l4d2_deathspit_trace_height 240.0
To reproduce this problem I just spawned a spitter bot and killed it with any gun. Walking around deathspit not touching visible textures made me a damage anyway.

**Comment by jensewe** [comment]
Hmm I don't think it's the one called invisible spit. You might want to check if the death spit is on uneven surface (small angled ramp for example), where part of the spit cannot be seen.

Perhaps it comes in inconsistently but it seems I managed to be damage-free as near as this for several times:

![image](https://user-images.githubusercontent.com/33988868/157686815-c7a5d798-034e-412a-a9ba-d2886208a72e.png)

**Comment by nikita1824** [comment]
Here is more [info](https://youtu.be/NcIRNLR8gfU). I hope it will be usefull.

**Comment by jensewe** [comment]
Thanks for the video.
Though I begin to wonder how vanilla death spit performs like, as I went through `l4d2_fix_deathspit` again which seems likely to prevent some part from being activated. So probably I've been wrong about what the invisible spit means.
It would be great that you can do me a favor to confirm whether vanilla deathspit

**Comment by nikita1824** [comment]
Yeah, vanilla deathspit has the same (or even worse) issue. Here is [demo](https://youtu.be/C76bgqV6uzE) which is recorded on local server with sv_cheats 1.

**Comment by jensewe** [comment]
Thanks a lot for keeping in contact, I've committed an update that should actually include the fix from the other plugin. Please see if that resolves the issue.

**Comment by nikita1824** [comment]
Hello again, too bad that I had to reopen issue about this plugin, now we have another problem. It's just error log spam but it's unpleasant to get them.
```
L 03/12/2022 - 18:30:36: SourceMod error session started
L 03/12/2022 - 18:30:36: Info (map "l4d2_stadium1_apartment") (file "/home/srcds/.steam/steamcmd/l4d2server/left4dead2/addons/sourcemod/logs/errors_20220312.log")
L 03/12/2022 - 18:30:36: [SM] Exception reported: Invalid memory access
L 03/12/2022 - 18:30:36: [SM] Blaming: l4d2_spit_spread_patch.smx
L 03/12/2022 - 18:30:36: [SM] Call stack trace:
L 03/12/2022 - 18:30:36: [SM]   [1] Line 208, D:\scripting\_plugins\l4d2_spit_spread_patch\scripting\l4d2_spit_spread_patch.sp::OnEntityCreated
L 03/12/2022 - 18:30:40: [SM] Exception reported: Invalid memory access
L 03/12/2022 - 18:30:40: [SM] Blaming: l4d2_spit_spread_patch.smx
L 03/12/2022 - 18:30:40: [SM] Call stack trace:
L 03/12/2022 - 18:30:40: [SM]   [1] Line 208, D:\scripting\_plugins\l4d2_spit_spread_patch\scripting\l4d2_spit_spread_patch.sp::OnEntityCreated
...
L 03/12/2022 - 18:50:28: Error log file session closed.
```
I'm not quite sure about this type of logs but it seems like if you try to get [7th symbol](https://github.com/Target5150/MoYu_Server_Stupid_Plugins/blob/master/The%20Last%20Stand/l4d2_spit_spread_patch/l4d2_spit_spread_patch.sp#L208) of classname string and its length is shorter, we get these errors.

**Comment by jensewe** [comment]
Good find! Thanks a lot, will commit an update soon.
