### ISSUE TITLE
Get up fixes can't compile error

### ISSUE THREAD

**Issue by lunatixxx** [Target5150/MoYu_Server_Stupid_Plugins#23]
Mainly the error 181

plugin.sp(85) : error 181: function argument named 'flag' differs from prototype
plugin.sp(88) : error 181: function argument named 'flag' differs from prototype
plugin.sp(252) : warning 213: tag mismatch
plugin.sp(253) : warning 213: tag mismatch
plugin.sp(254) : warning 213: tag mismatch
plugin.sp(255) : warning 213: tag mismatch
plugin.sp(271) : warning 213: tag mismatch
plugin.sp(296) : warning 213: tag mismatch
plugin.sp(297) : warning 213: tag mismatch
plugin.sp(298) : warning 213: tag mismatch
plugin.sp(313) : warning 213: tag mismatch
plugin.sp(314) : warning 213: tag mismatch
plugin.sp(324) : warning 213: tag mismatch
plugin.sp(340) : warning 213: tag mismatch
plugin.sp(348) : warning 213: tag mismatch
plugin.sp(349) : warning 213: tag mismatch
plugin.sp(350) : warning 213: tag mismatch
plugin.sp(351) : warning 213: tag mismatch
plugin.sp(375) : warning 213: tag mismatch
plugin.sp(376) : warning 213: tag mismatch
plugin.sp(382) : warning 213: tag mismatch
plugin.sp(383) : warning 213: tag mismatch
plugin.sp(386) : warning 213: tag mismatch
plugin.sp(387) : warning 213: tag mismatch
plugin.sp(393) : warning 213: tag mismatch
plugin.sp(393) : warning 213: tag mismatch
plugin.sp(404) : warning 213: tag mismatch
plugin.sp(405) : warning 213: tag mismatch
plugin.sp(445) : warning 213: tag mismatch
plugin.sp(446) : warning 213: tag mismatch
plugin.sp(447) : warning 213: tag mismatch
plugin.sp(448) : warning 213: tag mismatch
plugin.sp(472) : warning 213: tag mismatch
plugin.sp(478) : warning 213: tag mismatch
plugin.sp(483) : warning 213: tag mismatch
plugin.sp(484) : warning 213: tag mismatch
plugin.sp(485) : warning 213: tag mismatch
plugin.sp(510) : warning 213: tag mismatch
plugin.sp(516) : warning 213: tag mismatch
plugin.sp(521) : warning 213: tag mismatch
plugin.sp(522) : warning 213: tag mismatch
plugin.sp(523) : warning 213: tag mismatch

**Comment by lunatixxx** [comment]
Another random error in logs:

L 06/29/2022 - 19:32:00: [SM] Exception reported: Invalid convar handle 0 (error 4)
L 06/29/2022 - 19:32:00: [SM] Blaming: l4d2_getup_fixes.smx
L 06/29/2022 - 19:32:00: [SM] Call stack trace:
L 06/29/2022 - 19:32:00: [SM]   [0] ConVar.FloatValue.get
L 06/29/2022 - 19:32:00: [SM]   [1] Line 395, plugin.sp::Event_ChargerKilled

**Comment by lunatixxx** [comment]
new error popped.

L 07/24/2022 - 01:32:49: [SM] Exception reported: Invalid convar handle 0 (error 4)
L 07/24/2022 - 01:32:49: [SM] Blaming: l4d2_getup_fixes.smx
L 07/24/2022 - 01:32:49: [SM] Call stack trace:
L 07/24/2022 - 01:32:49: [SM]   [0] ConVar.FloatValue.get
L 07/24/2022 - 01:32:49: [SM]   [1] Line 395, plugin.sp::Event_ChargerKilled

**Comment by lunatixxx** [comment]
This error popped again and i have the last version of godframes plugin.

**Comment by jensewe** [comment]
It's likely that you are not using confogl for config management and plugins are loaded by default startup, in this way the plugin probably won't emit an error of dependency missing while the convar isn't prepared at the time.
I will try fixing this in a PR soon.

**Comment by lunatixxx** [comment]
I am using confogl but not config management as there is only one, it's modified a little.

**Comment by vikingo12** [comment]
> I am using confogl but not config management as there is only one, it's modified a little.

do u have l4d2util?

**Comment by lunatixxx** [comment]
yes

> > I am using confogl but not config management as there is only one, it's modified a little.
> 
> do u have l4d2util?

**Comment by lunatixxx** [comment]
By the way i think this is related to that but this cause a bug when you kill charger where you see transparency for survivor godframes, even if i disabled it.

**Comment by jensewe** [comment]
`l4d2util` currently has become a script library as the plugin has nothing significant for developers, I don't think there's anything to do with it.

> By the way i think this is related to that this cause a bug when you kill charger where you see transparency for survivor godframes, even if i disabled these.

It's an [internal issue with `l4d2_godframes_control_merge`](https://github.com/SirPlease/L4D2-Competitive-Rework/blob/47e29724e35b0ca276f1130049205fe565117db9/addons/sourcemod/scripting/l4d2_godframes_control_merge.sp#L965-L967) where the glow ConVar isn't respected in the native callback, meaning that godframes added by `l4d2_getup_fixes` will always color the survivors.

**Comment by lunatixxx** [comment]
> 

Is it possible to fix it ? The transparency.

**Comment by jensewe** [comment]
Sorry, didn't notice that one. I've made a PR at Sir's repo, should be fixed now.

**Comment by lunatixxx** [comment]
So the error is back apparently after i updated to last versions. I did not see anymore the transparency so at least that seems fixed.

L 08/06/2022 - 17:01:26: [SM] Exception reported: Invalid convar handle 0 (error 4)
L 08/06/2022 - 17:01:26: [SM] Blaming: l4d2_getup_fixes.smx
L 08/06/2022 - 17:01:26: [SM] Call stack trace:
L 08/06/2022 - 17:01:26: [SM]   [0] ConVar.FloatValue.get
L 08/06/2022 - 17:01:26: [SM]   [1] Line 395, plugin.sp::Event_ChargerKilled
L 08/06/2022 - 17:09:04: Error log file session closed.
